config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root to: 'questions#index'

  resources :users, except: [:index, :edit, :update]
  resources :questions, except: [:index] do
    resources :answers, except: [:index, :show] do
      resources :votes, only: [:create]
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :search, only: [:index]
end

app/models/answer.rb
class Answer < ActiveRecord::Base

  validates :answer, :question_id, :user_id, presence: true
  belongs_to :question
  belongs_to :user
  has_many :votes
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, presence: true
  validates :question, presence: true
  validates :user_id, presence: true
  belongs_to :user
  has_many :answers #, foreign_key: 'question_id', class_name: 'Answer'
  belongs_to :favorite, class_name: 'Answer'

  def self.search(search)
     where("title like ? or question like ?", "%#{search}%", "%#{search}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, :email, presence: true, uniqueness: true
  has_many :questions
  has_many :votes
  has_many :answers, through: :questions
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  validates :user_id, :answer_id, presence: true
  belongs_to :user
  belongs_to :answer
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authorize, only: [:new]

  def new
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new
    respond_to do |format|
      format.html { redirect_to question_path(@question) }
      format.js
    end
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    respond_to do |format|
      if @answer.save
          format.html { redirect_to question_path(@question), notice: 'Answer submitted' }
          format.js
      else
        blah
      end
    end
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(answer_params)
    @answer.update(:favorite_id)
    respond_to
  end

private
  def answer_params
    params.require(:answer).permit(:answer, :user_id, :question_id).merge(:user_id => current_user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] && User.exists?(session[:user_id])
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authorize, except: [:index, :show]

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    current_user = User.find(session[:user_id])
    @question = current_user.questions.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:notice] = 'Question asked'
      redirect_to question_path(@question)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(session[:user_id])
    @question = @user.questions.find(params[:id])
  end

  def update
    @user = User.find(session[:user_id])
    @question = @user.questions.find(params[:id])
    if @question.update(question_params)
      flash[:notice] = 'Question updated'
      redirect_to question_path(@question)
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:alert] = 'Question deleted'
    redirect_to user_path(@question.user.id)
  end

private
  def question_params
    params.require(:question).permit(:title, :question, :user_id).merge(user_id: current_user.id )
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @search = Question.search params[:search]
      redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = 'Logged in'
      redirect_to root_path
    else
      flash.now.alert = 'Login is invalid'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'User logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: :destroy

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'Account successfully created'
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:alert] = 'Account deleted'
    redirect_to root_path
  end

private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    @answer = Answer.find(params[:answer_id])
    @votes = @answer.votes.new(vote_params)
    if @votes.save
      flash[:notice] = "You have voted on this answer!"
      respond_to do |format|
        format.html {redirect_to question_path(@question)}
        format.js
      end
    end
  end
private
  def vote_params
    params.permit(:answer_id, :user_id).merge(:user_id => current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer.html.erb
<p><%= answer.answer %></p>
<p>Submitted by: <%= answer.user.name %>, <%= time_ago_in_words(answer.created_at) %> ago</p>

<%= link_to "Upvote Answer", question_answer_votes_path(@question, answer), remote: true, data: { method: 'post' }, id: "vote_link" %>
<p id='vote_count_<%= answer.id %>'><%= answer.votes.count %></p>

<%#= form_for @question do |f| %>
  <%#= f.hidden_field :favorite_id, :value => answer.id %>
  <%#= f.submit 'Favorite' %>
<%# end %>

app/views/answers/_form.html.erb
<%= form_for [@question, @answer], id: 'answer-form', remote: true do |f| %>
  <%= f.label :answer %>
  <%= f.text_area :answer, size: '20x25' %>
  <%= f.submit 'Submit Answer' %>
<% end %>

app/views/answers/create.js.erb
$('#new_answer').remove();
$('#answer-link').show();
$('#answers').append("<%= j render 'answers/answer', answer: @answer %>");

app/views/answers/new.js.erb
$('#answer-link').hide().after('<%= j render "form" %>');

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class='error_messages'>
    <h3>Please fix the following errors:</h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
    <p>Logged in as <%= link_to current_user.name, user_path(current_user) %></p>
    <%= link_to 'Log Out', logout_path %>
  <% else %>
    <p><%= link_to 'Sign Up', signup_path %> or
       <%= link_to 'Log In', login_path %></p>
  <% end %>

  <%= flash[:alert] %>
  <%= flash[:notice] %>
  <%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for [@question] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :question %>
  <%= f.text_area :question, size: '20x20' %>
  <%= f.submit 'Submit Question' %>
<% end %>

app/views/questions/edit.html.erb
<% content_for(:title, 'Edit Question | StackOverflow') %>

<h1>Edit Question</h1>

<%= render 'layouts/errors', object: @question %>

<%= render 'form' %>

app/views/questions/index.html.erb
<% content_for(:title, 'StackOverflow') %>

<h1>Index Page</h1>

<% @questions.each do |question| %>
  <div>
    <%= link_to question.title, question_path(question) %></a>
    <p>asked <%= time_ago_in_words(question.created_at) %> ago by <%= link_to question.user.name, user_path(question.user.id) %></a></p>
    <br />
  </div>
<% end %>

<h2>Search for a Question: </h2>
<div>
   <%= form_tag(search_index_path, :method => 'get' do %>
      <%= text_field_tag :search, params[:search], :id => 'search_field' %>
      <%= submit_tag "Search", :name => nil %>
    <% end %>
</div>

<h2>Search Results: </h2>

<ul>
    <% @search.each do |search| %>
  <li><%= link_to grant.title,
    :action => 'show', :id => grant.id  %></li>
  <% end %>
</ul>

app/views/questions/new.html.erb
<% content_for(:title, 'New Question | StackOverflow') %>

<h1>Ask A Question</h1>

<%= render 'layouts/errors', object: @question %>

<%= render 'form' %>

app/views/questions/show.html.erb
<% content_for(:title, 'Question') %>

<h1><%= @question.title %></h1>

<p><%= @question.question %></p>

<p>asked <%= time_ago_in_words(@question.created_at) %> ago</p>

<p><%= link_to @question.user.name, user_path(@question.user.id) %></p>

<% if current_user %>
  <p><%= link_to 'Answer', new_question_answer_path(@question.id), id: "answer-link", remote: true %></p>
<% else %>
  <p>Login in to answer </p>
<% end %>

<div id='answers'>
  <%= render @question.answers %>
</div>


<%= link_to 'Main_menu', root_path %>

<% if current_user && @question.user.id == current_user.id %>
  <p><%= link_to 'Delete', question_path(@question), data: { confirm: 'Are you sure you want to delete this question?',
                                                              method: 'delete' }
                                                              %></p>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit(:class => 'btn btn-success') %>
<% end %>

app/views/users/new.html.erb
<% content_for(:title, 'Sign Up | StackOverflow') %>
<h1>Create An Account</h1>

<%= render 'layouts/errors', object: @user %>

<%= render 'form' %>

app/views/users/show.html.erb
<% content_for(:title, 'Profile | StackOverflow') %>
<h1>Profile</h1>

<h2><%= @user.name %></div>

<h3>Questions</h3>
<% @user.questions.each do |question| %>
  <h4><%=  link_to question.title, question_path(question.id) %></h4>
<% end %>
<br />

<p><%= link_to 'Main Menu', root_path %></p>
<p><%= link_to 'New Question', new_question_path %></p>

<% if current_user && @user.id == current_user.id %>
  <%= link_to "Delete account", user_path(@user),
            data: { confirm: "Are you sure you want to delete this account",
            method: 'delete' }
            %>
<% end %>

app/views/votes/create.js.erb
$('#vote_count_<%= @answer.id %>').replaceWith('<p id="vote_count_<%= @answer.id %>"><%= @answer.votes.count %></p>');